package poo;

public class Interfaces_ClasesInternas {

	public static void main(String[] args) {


		/*INTERFACES - CLASES INTERNAS
		 * 
		 * 
		 * CONJUNTO DE DIRECTRICES/METODOS QUE DEBEN CUMPLIR LAS CLASES
		 * 
		 * UNA CLASE PUEDE HEREDAR DE UNA INTERFAZ
		 * LAS INTERFACES ESTABLECEN COMPORTAMIENTOS (DIRECTRICES) A CUMPLIR POR LAS CLASES QUE IMPLEMENTAS ESAS INTERFACES
		 * 
		 * CARACTERISTICAS DE LAS INTERFACES:
		 * 
		 * INTERFAZ-->|SOLO CONTIENEN|-->|METODOS ABSTRACTOS|
		 * 		   					 |-->|CONSTANTES|
		 * 
		 * - SE ALAMCENEN EN UN FICHEROS .CLASS --> SOLO SE DEFIENEN LOS METODOS
		 * - NO SE PUEDEN INSTANCIAR (NO USO DE NEW)
		 * - TODOS SUS METODOS SON PULIC Y ABSTRAC. NO SE IMPLEMNETAN
		 * - NO TIENEN VARIABLES
		 * - SI TIENEN CONSTANTES
		 * 
		 * DETERMINAR EL COMPORTAMIENTO DE AQUELLAS CLASES QUE INCLUYEN ESAS INTERFACES
		 * QUE TIENEN METODOS ABTRACTOS 
		 * 
		 * 
		 * PORQUE NECESARIAS LAS INTERFACES??
		 * 
		 * NO PUEDEN TENER METODOS NORMLAES, TODOS TIENEN QUE SER ABSTRACTOS
		 * 
		 * PARA RESOLVER LA HERENCIA SIMPLE, Y PODER TENER HERENCIA MULTIPLE:
		 * OSEA PODER HEREDAR EN UNA CLASE DE VARIAS--> (INTERFACES)
		 * 
		 * EJEM --> CLASS EXTENDS EMPLEADO IMPLEMENTS INTERFAZ1, INTERFAZ2
		 * 
		 * NOTA: EN LA DOCUMENTACION DE JAVA EN EL PANEL DE ACCESO A TODOS LAS CLASES
		 * ALGUNOS NOMBRES TIENE SU TITULO EN CURSIVA ESTO SIGNIFICA QUE SON INTERFACES
		 * 
		 * 
		 * *****INTERFACES 2*************
		 * 
		 * PRIPIEDADES DE LAS INTERFACES
		 * - ESTAS NO SE PUEDEN INSTANCIAR
		 * 
		 * 
		 * 
		 * 
		 */

	}

}
