package poo;

public class ModificadoresAcceso_SuperClaseCosmica {

	public static void main(String[] args) {

	/*
	 * MODIFICADORES DE ACCESO - LA CLASE OBJECT(SUPER CLASE COSMICA)
	 * 
	 * 
	 * MODIFICADORES DE ACCESO
	 * 
	 * MODIFICADOR		CLASE		PACKAGE		SUBCLASE		TODOS
	 * PUBLIC			SI			SI			SI				SI		
	 * PROTECTED		SI			SI			SI				NO
	 * PRIVATE			SI			NO			NO				NO
	 * POR DEFECTO		SI			SI			NO				NO
	 * 
	 * PROTECTED --> NO SERA ACCESIBLE DESDE UNA CLASE 
	 * QUE NO SEA SUBCLASE QUE SEA DE UN PAQUETE DIFERNETE
	 * 
	 * PRIVATE --> SU ACCESO SOLO ES SOBRE SU MISMA CLASE
	 * POR DEFECTO --> NO TIENE ACCESO A SUBCLASES DE OTROS PAQUETES
	 * 
	 * 
	 * 
	 * LA CLASE OBJECT (SUPER CLASE COSMICA):
	 * 
	 * ES LA CLASE QUE ESTA EN LA CUSPOEDE DE TODAS LA CLASES DE JAVA
	 * TODAS LAS CLASES HEREDAN DE ESTA CLASE OBJECT.
	 * 
	 * AUMOTICAMENTE SE HEREDA DE LA CLASE OBJECT
	 * 
	 * 
	 * 
	 */

	}

}
